apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo1
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-demo
          image: 'nginx:1.14.2'
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 1.0m
              memory: 3.0Mi

