apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-nginx-demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: nginx-demo
          image: 'nginx:1.14.2'
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 2.0m
              memory: 4.0Mi
