apiVersion: apps/v1
kind: Deployment
metadata:
  name: vartest-nginx-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: vartest-nginx
          image: 'nginx:1.14.2'
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 100.0m
              memory: 2.0Mi
        - name: vartest-nginx-logs
          image: 'nginx:1.14.2'
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 0.1m
              memory: 1024Mi
