apiVersion: apps/v1
kind: Deployment
metadata:
  name: vartest-nginx-server
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: vartest-nginx
          image: 'nginx:1.14.2'
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 100.0m
              memory: 1024.0Mi
        - name: vartest-nginx-logs
          image: 'nginx:1.14.2'
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 500m
              memory: 1.0Gi
            requests:
              cpu: 100.0m
              memory: 1024.0Mi
