apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-nginx-repo
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: nginx-repo
          image: 'nginx:1.14.2'
          resources:
            limits:
              cpu: 500m
              memory: 8.0Gi
            requests:
              cpu: 2.0m
              memory: 6.0Mi
